# Compiler Parallel/Serial
ifdef MPIPRG
  CXX = mpicxx
  FC = mpif90
else
  CXX = g++
  FC = gfortran
endif

# Linker
LD = $(FC)

# Archiver
AR = ar

# Optimization level
CXXFLAGS  = -O2 -g

FFLAGS = -O2 -fconvert=big-endian -g
#FFLAGS = -O0 -pg -fconvert=big-endian -Wall -Wextra -pedantic -fimplicit-none -fbounds-check -fbacktrace -ffpe-trap=zero,overflow,underflow 

# Linking flags
LDFLAGS = $(FFLAGS)

LIBFLAGS=-lstdc++

# Archiver flags
ARFLAGS = rv

# Indexing the archive
RANLIB  = ranlib
